name: Weekly DBT Job

on:
  schedule:
    - cron: "0 4 * * 0" # Runs every Sunday at 4 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.9.2 dbt-snowflake==1.9.1

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "
          dbt_assignment_2:
            outputs:
              dev:
                type: snowflake
                account: ${{ secrets.DBT_ACCOUNT }}
                user: ${{ secrets.DBT_USER }}
                password: ${{ secrets.DBT_PASSWORD }}
                role: ${{ secrets.DBT_ROLE }}
                warehouse: ${{ secrets.DBT_WAREHOUSE }}
                database: ${{ secrets.DBT_DATABASE }}
                schema: ${{ secrets.DBT_SCHEMA }}
                threads: 4
            target: dev
          " > ~/.dbt/profiles.yml

      - name: Run dbt commands
        run: |
          dbt debug
          dbt deps
          dbt compile
          dbt build
          dbt run --full-refresh
