name: dbt CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
          dbt_assignment_2:
            outputs:
              dev:
                type: snowflake
                account: "${{ secrets.DBT_ACCOUNT }}"
                user: "${{ secrets.DBT_USER }}"
                password: "${{ secrets.DBT_PASSWORD }}"
                role: "${{ secrets.DBT_ROLE }}"
                warehouse: "${{ secrets.DBT_WAREHOUSE }}"
                database: "${{ secrets.DBT_DATABASE }}"
                schema: "${{ secrets.DBT_SCHEMA }}"
                threads: 4
            target: dev
          EOL

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.9.2 dbt-snowflake==1.9.1

      - name: Run dbt commands
        run: |
          dbt debug
          dbt deps
          dbt compile

      - name: Run dbt build
        run: |
          dbt build
